/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupOrganizationRouteImport } from './routes/setup-organization'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug.index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as OrgSlugWorkersRouteImport } from './routes/$orgSlug.workers'
import { Route as OrgSlugTeamRouteImport } from './routes/$orgSlug.team'
import { Route as OrgSlugSettingsRouteImport } from './routes/$orgSlug.settings'
import { Route as OrgSlugScheduledJobsRouteImport } from './routes/$orgSlug.scheduled-jobs'
import { Route as OrgSlugRedisKeysRouteImport } from './routes/$orgSlug.redis-keys'
import { Route as OrgSlugConnectionsRouteImport } from './routes/$orgSlug.connections'
import { Route as OrgSlugAnalyticsRouteImport } from './routes/$orgSlug.analytics'
import { Route as OrgSlugAlertsRouteImport } from './routes/$orgSlug.alerts'
import { Route as OrgSlugSettingsIndexRouteImport } from './routes/$orgSlug.settings.index'
import { Route as OrgSlugSettingsTeamRouteImport } from './routes/$orgSlug.settings.team'
import { Route as OrgSlugSettingsIntegrationsRouteImport } from './routes/$orgSlug.settings.integrations'
import { Route as OrgSlugSettingsDestinationsRouteImport } from './routes/$orgSlug.settings.destinations'
import { Route as OrgSlugSettingsConnectionsRouteImport } from './routes/$orgSlug.settings.connections'
import { Route as OrgSlugSettingsAuthenticationRouteImport } from './routes/$orgSlug.settings.authentication'
import { Route as OrgSlugSettingsAppearanceRouteImport } from './routes/$orgSlug.settings.appearance'
import { Route as OrgSlugSettingsAboutRouteImport } from './routes/$orgSlug.settings.about'
import { Route as OrgSlugCConnectionIdRouteImport } from './routes/$orgSlug.c.$connectionId'
import { Route as OrgSlugCConnectionIdIndexRouteImport } from './routes/$orgSlug.c.$connectionId.index'
import { Route as OrgSlugCConnectionIdWorkersRouteImport } from './routes/$orgSlug.c.$connectionId.workers'
import { Route as OrgSlugCConnectionIdScheduledJobsRouteImport } from './routes/$orgSlug.c.$connectionId.scheduled-jobs'
import { Route as OrgSlugCConnectionIdRedisKeysRouteImport } from './routes/$orgSlug.c.$connectionId.redis-keys'
import { Route as OrgSlugCConnectionIdAnalyticsRouteImport } from './routes/$orgSlug.c.$connectionId.analytics'
import { Route as OrgSlugCConnectionIdAlertsRouteImport } from './routes/$orgSlug.c.$connectionId.alerts'
import { Route as OrgSlugCConnectionIdAlertsIndexRouteImport } from './routes/$orgSlug.c.$connectionId.alerts.index'
import { Route as OrgSlugCConnectionIdQueuesQueueNameRouteImport } from './routes/$orgSlug.c.$connectionId.queues.$queueName'
import { Route as OrgSlugCConnectionIdAlertsNewRouteImport } from './routes/$orgSlug.c.$connectionId.alerts.new'
import { Route as OrgSlugCConnectionIdAlertsRuleIdRouteImport } from './routes/$orgSlug.c.$connectionId.alerts.$ruleId'
import { Route as OrgSlugCConnectionIdAlertsRulesIndexRouteImport } from './routes/$orgSlug.c.$connectionId.alerts.rules.index'
import { Route as OrgSlugCConnectionIdAlertsRulesRuleIdRouteImport } from './routes/$orgSlug.c.$connectionId.alerts.rules.$ruleId'
import { Route as OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRouteImport } from './routes/$orgSlug.c.$connectionId.queues.$queueName_.scheduled-jobs.new'
import { Route as OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRouteImport } from './routes/$orgSlug.c.$connectionId.queues.$queueName_.scheduled-jobs.$schedulerId'
import { Route as OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRouteImport } from './routes/$orgSlug.c.$connectionId.queues.$queueName_.jobs.$jobId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupOrganizationRoute = SetupOrganizationRouteImport.update({
  id: '/setup-organization',
  path: '/setup-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugRoute,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugWorkersRoute = OrgSlugWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugTeamRoute = OrgSlugTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsRoute = OrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugScheduledJobsRoute = OrgSlugScheduledJobsRouteImport.update({
  id: '/scheduled-jobs',
  path: '/scheduled-jobs',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugRedisKeysRoute = OrgSlugRedisKeysRouteImport.update({
  id: '/redis-keys',
  path: '/redis-keys',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugConnectionsRoute = OrgSlugConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugAnalyticsRoute = OrgSlugAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugAlertsRoute = OrgSlugAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const OrgSlugSettingsTeamRoute = OrgSlugSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const OrgSlugSettingsIntegrationsRoute =
  OrgSlugSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const OrgSlugSettingsDestinationsRoute =
  OrgSlugSettingsDestinationsRouteImport.update({
    id: '/destinations',
    path: '/destinations',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const OrgSlugSettingsConnectionsRoute =
  OrgSlugSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const OrgSlugSettingsAuthenticationRoute =
  OrgSlugSettingsAuthenticationRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const OrgSlugSettingsAppearanceRoute =
  OrgSlugSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => OrgSlugSettingsRoute,
  } as any)
const OrgSlugSettingsAboutRoute = OrgSlugSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => OrgSlugSettingsRoute,
} as any)
const OrgSlugCConnectionIdRoute = OrgSlugCConnectionIdRouteImport.update({
  id: '/c/$connectionId',
  path: '/c/$connectionId',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugCConnectionIdIndexRoute =
  OrgSlugCConnectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)
const OrgSlugCConnectionIdWorkersRoute =
  OrgSlugCConnectionIdWorkersRouteImport.update({
    id: '/workers',
    path: '/workers',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)
const OrgSlugCConnectionIdScheduledJobsRoute =
  OrgSlugCConnectionIdScheduledJobsRouteImport.update({
    id: '/scheduled-jobs',
    path: '/scheduled-jobs',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)
const OrgSlugCConnectionIdRedisKeysRoute =
  OrgSlugCConnectionIdRedisKeysRouteImport.update({
    id: '/redis-keys',
    path: '/redis-keys',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)
const OrgSlugCConnectionIdAnalyticsRoute =
  OrgSlugCConnectionIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)
const OrgSlugCConnectionIdAlertsRoute =
  OrgSlugCConnectionIdAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)
const OrgSlugCConnectionIdAlertsIndexRoute =
  OrgSlugCConnectionIdAlertsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgSlugCConnectionIdAlertsRoute,
  } as any)
const OrgSlugCConnectionIdQueuesQueueNameRoute =
  OrgSlugCConnectionIdQueuesQueueNameRouteImport.update({
    id: '/queues/$queueName',
    path: '/queues/$queueName',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)
const OrgSlugCConnectionIdAlertsNewRoute =
  OrgSlugCConnectionIdAlertsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => OrgSlugCConnectionIdAlertsRoute,
  } as any)
const OrgSlugCConnectionIdAlertsRuleIdRoute =
  OrgSlugCConnectionIdAlertsRuleIdRouteImport.update({
    id: '/$ruleId',
    path: '/$ruleId',
    getParentRoute: () => OrgSlugCConnectionIdAlertsRoute,
  } as any)
const OrgSlugCConnectionIdAlertsRulesIndexRoute =
  OrgSlugCConnectionIdAlertsRulesIndexRouteImport.update({
    id: '/rules/',
    path: '/rules/',
    getParentRoute: () => OrgSlugCConnectionIdAlertsRoute,
  } as any)
const OrgSlugCConnectionIdAlertsRulesRuleIdRoute =
  OrgSlugCConnectionIdAlertsRulesRuleIdRouteImport.update({
    id: '/rules/$ruleId',
    path: '/rules/$ruleId',
    getParentRoute: () => OrgSlugCConnectionIdAlertsRoute,
  } as any)
const OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRoute =
  OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRouteImport.update({
    id: '/queues/$queueName_/scheduled-jobs/new',
    path: '/queues/$queueName/scheduled-jobs/new',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)
const OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRoute =
  OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRouteImport.update(
    {
      id: '/queues/$queueName_/scheduled-jobs/$schedulerId',
      path: '/queues/$queueName/scheduled-jobs/$schedulerId',
      getParentRoute: () => OrgSlugCConnectionIdRoute,
    } as any,
  )
const OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRoute =
  OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRouteImport.update({
    id: '/queues/$queueName_/jobs/$jobId',
    path: '/queues/$queueName/jobs/$jobId',
    getParentRoute: () => OrgSlugCConnectionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup-organization': typeof SetupOrganizationRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/alerts': typeof OrgSlugAlertsRoute
  '/$orgSlug/analytics': typeof OrgSlugAnalyticsRoute
  '/$orgSlug/connections': typeof OrgSlugConnectionsRoute
  '/$orgSlug/redis-keys': typeof OrgSlugRedisKeysRoute
  '/$orgSlug/scheduled-jobs': typeof OrgSlugScheduledJobsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/team': typeof OrgSlugTeamRoute
  '/$orgSlug/workers': typeof OrgSlugWorkersRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/c/$connectionId': typeof OrgSlugCConnectionIdRouteWithChildren
  '/$orgSlug/settings/about': typeof OrgSlugSettingsAboutRoute
  '/$orgSlug/settings/appearance': typeof OrgSlugSettingsAppearanceRoute
  '/$orgSlug/settings/authentication': typeof OrgSlugSettingsAuthenticationRoute
  '/$orgSlug/settings/connections': typeof OrgSlugSettingsConnectionsRoute
  '/$orgSlug/settings/destinations': typeof OrgSlugSettingsDestinationsRoute
  '/$orgSlug/settings/integrations': typeof OrgSlugSettingsIntegrationsRoute
  '/$orgSlug/settings/team': typeof OrgSlugSettingsTeamRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/c/$connectionId/alerts': typeof OrgSlugCConnectionIdAlertsRouteWithChildren
  '/$orgSlug/c/$connectionId/analytics': typeof OrgSlugCConnectionIdAnalyticsRoute
  '/$orgSlug/c/$connectionId/redis-keys': typeof OrgSlugCConnectionIdRedisKeysRoute
  '/$orgSlug/c/$connectionId/scheduled-jobs': typeof OrgSlugCConnectionIdScheduledJobsRoute
  '/$orgSlug/c/$connectionId/workers': typeof OrgSlugCConnectionIdWorkersRoute
  '/$orgSlug/c/$connectionId/': typeof OrgSlugCConnectionIdIndexRoute
  '/$orgSlug/c/$connectionId/alerts/$ruleId': typeof OrgSlugCConnectionIdAlertsRuleIdRoute
  '/$orgSlug/c/$connectionId/alerts/new': typeof OrgSlugCConnectionIdAlertsNewRoute
  '/$orgSlug/c/$connectionId/queues/$queueName': typeof OrgSlugCConnectionIdQueuesQueueNameRoute
  '/$orgSlug/c/$connectionId/alerts/': typeof OrgSlugCConnectionIdAlertsIndexRoute
  '/$orgSlug/c/$connectionId/alerts/rules/$ruleId': typeof OrgSlugCConnectionIdAlertsRulesRuleIdRoute
  '/$orgSlug/c/$connectionId/alerts/rules/': typeof OrgSlugCConnectionIdAlertsRulesIndexRoute
  '/$orgSlug/c/$connectionId/queues/$queueName/jobs/$jobId': typeof OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRoute
  '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/$schedulerId': typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRoute
  '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/new': typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-error': typeof AuthErrorRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup-organization': typeof SetupOrganizationRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/alerts': typeof OrgSlugAlertsRoute
  '/$orgSlug/analytics': typeof OrgSlugAnalyticsRoute
  '/$orgSlug/connections': typeof OrgSlugConnectionsRoute
  '/$orgSlug/redis-keys': typeof OrgSlugRedisKeysRoute
  '/$orgSlug/scheduled-jobs': typeof OrgSlugScheduledJobsRoute
  '/$orgSlug/team': typeof OrgSlugTeamRoute
  '/$orgSlug/workers': typeof OrgSlugWorkersRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/$orgSlug/settings/about': typeof OrgSlugSettingsAboutRoute
  '/$orgSlug/settings/appearance': typeof OrgSlugSettingsAppearanceRoute
  '/$orgSlug/settings/authentication': typeof OrgSlugSettingsAuthenticationRoute
  '/$orgSlug/settings/connections': typeof OrgSlugSettingsConnectionsRoute
  '/$orgSlug/settings/destinations': typeof OrgSlugSettingsDestinationsRoute
  '/$orgSlug/settings/integrations': typeof OrgSlugSettingsIntegrationsRoute
  '/$orgSlug/settings/team': typeof OrgSlugSettingsTeamRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/c/$connectionId/analytics': typeof OrgSlugCConnectionIdAnalyticsRoute
  '/$orgSlug/c/$connectionId/redis-keys': typeof OrgSlugCConnectionIdRedisKeysRoute
  '/$orgSlug/c/$connectionId/scheduled-jobs': typeof OrgSlugCConnectionIdScheduledJobsRoute
  '/$orgSlug/c/$connectionId/workers': typeof OrgSlugCConnectionIdWorkersRoute
  '/$orgSlug/c/$connectionId': typeof OrgSlugCConnectionIdIndexRoute
  '/$orgSlug/c/$connectionId/alerts/$ruleId': typeof OrgSlugCConnectionIdAlertsRuleIdRoute
  '/$orgSlug/c/$connectionId/alerts/new': typeof OrgSlugCConnectionIdAlertsNewRoute
  '/$orgSlug/c/$connectionId/queues/$queueName': typeof OrgSlugCConnectionIdQueuesQueueNameRoute
  '/$orgSlug/c/$connectionId/alerts': typeof OrgSlugCConnectionIdAlertsIndexRoute
  '/$orgSlug/c/$connectionId/alerts/rules/$ruleId': typeof OrgSlugCConnectionIdAlertsRulesRuleIdRoute
  '/$orgSlug/c/$connectionId/alerts/rules': typeof OrgSlugCConnectionIdAlertsRulesIndexRoute
  '/$orgSlug/c/$connectionId/queues/$queueName/jobs/$jobId': typeof OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRoute
  '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/$schedulerId': typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRoute
  '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/new': typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/auth-error': typeof AuthErrorRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup-organization': typeof SetupOrganizationRoute
  '/signup': typeof SignupRoute
  '/$orgSlug/alerts': typeof OrgSlugAlertsRoute
  '/$orgSlug/analytics': typeof OrgSlugAnalyticsRoute
  '/$orgSlug/connections': typeof OrgSlugConnectionsRoute
  '/$orgSlug/redis-keys': typeof OrgSlugRedisKeysRoute
  '/$orgSlug/scheduled-jobs': typeof OrgSlugScheduledJobsRoute
  '/$orgSlug/settings': typeof OrgSlugSettingsRouteWithChildren
  '/$orgSlug/team': typeof OrgSlugTeamRoute
  '/$orgSlug/workers': typeof OrgSlugWorkersRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/$orgSlug/c/$connectionId': typeof OrgSlugCConnectionIdRouteWithChildren
  '/$orgSlug/settings/about': typeof OrgSlugSettingsAboutRoute
  '/$orgSlug/settings/appearance': typeof OrgSlugSettingsAppearanceRoute
  '/$orgSlug/settings/authentication': typeof OrgSlugSettingsAuthenticationRoute
  '/$orgSlug/settings/connections': typeof OrgSlugSettingsConnectionsRoute
  '/$orgSlug/settings/destinations': typeof OrgSlugSettingsDestinationsRoute
  '/$orgSlug/settings/integrations': typeof OrgSlugSettingsIntegrationsRoute
  '/$orgSlug/settings/team': typeof OrgSlugSettingsTeamRoute
  '/$orgSlug/settings/': typeof OrgSlugSettingsIndexRoute
  '/$orgSlug/c/$connectionId/alerts': typeof OrgSlugCConnectionIdAlertsRouteWithChildren
  '/$orgSlug/c/$connectionId/analytics': typeof OrgSlugCConnectionIdAnalyticsRoute
  '/$orgSlug/c/$connectionId/redis-keys': typeof OrgSlugCConnectionIdRedisKeysRoute
  '/$orgSlug/c/$connectionId/scheduled-jobs': typeof OrgSlugCConnectionIdScheduledJobsRoute
  '/$orgSlug/c/$connectionId/workers': typeof OrgSlugCConnectionIdWorkersRoute
  '/$orgSlug/c/$connectionId/': typeof OrgSlugCConnectionIdIndexRoute
  '/$orgSlug/c/$connectionId/alerts/$ruleId': typeof OrgSlugCConnectionIdAlertsRuleIdRoute
  '/$orgSlug/c/$connectionId/alerts/new': typeof OrgSlugCConnectionIdAlertsNewRoute
  '/$orgSlug/c/$connectionId/queues/$queueName': typeof OrgSlugCConnectionIdQueuesQueueNameRoute
  '/$orgSlug/c/$connectionId/alerts/': typeof OrgSlugCConnectionIdAlertsIndexRoute
  '/$orgSlug/c/$connectionId/alerts/rules/$ruleId': typeof OrgSlugCConnectionIdAlertsRulesRuleIdRoute
  '/$orgSlug/c/$connectionId/alerts/rules/': typeof OrgSlugCConnectionIdAlertsRulesIndexRoute
  '/$orgSlug/c/$connectionId/queues/$queueName_/jobs/$jobId': typeof OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRoute
  '/$orgSlug/c/$connectionId/queues/$queueName_/scheduled-jobs/$schedulerId': typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRoute
  '/$orgSlug/c/$connectionId/queues/$queueName_/scheduled-jobs/new': typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/auth-error'
    | '/consent'
    | '/login'
    | '/settings'
    | '/setup-organization'
    | '/signup'
    | '/$orgSlug/alerts'
    | '/$orgSlug/analytics'
    | '/$orgSlug/connections'
    | '/$orgSlug/redis-keys'
    | '/$orgSlug/scheduled-jobs'
    | '/$orgSlug/settings'
    | '/$orgSlug/team'
    | '/$orgSlug/workers'
    | '/invite/$invitationId'
    | '/$orgSlug/'
    | '/$orgSlug/c/$connectionId'
    | '/$orgSlug/settings/about'
    | '/$orgSlug/settings/appearance'
    | '/$orgSlug/settings/authentication'
    | '/$orgSlug/settings/connections'
    | '/$orgSlug/settings/destinations'
    | '/$orgSlug/settings/integrations'
    | '/$orgSlug/settings/team'
    | '/$orgSlug/settings/'
    | '/$orgSlug/c/$connectionId/alerts'
    | '/$orgSlug/c/$connectionId/analytics'
    | '/$orgSlug/c/$connectionId/redis-keys'
    | '/$orgSlug/c/$connectionId/scheduled-jobs'
    | '/$orgSlug/c/$connectionId/workers'
    | '/$orgSlug/c/$connectionId/'
    | '/$orgSlug/c/$connectionId/alerts/$ruleId'
    | '/$orgSlug/c/$connectionId/alerts/new'
    | '/$orgSlug/c/$connectionId/queues/$queueName'
    | '/$orgSlug/c/$connectionId/alerts/'
    | '/$orgSlug/c/$connectionId/alerts/rules/$ruleId'
    | '/$orgSlug/c/$connectionId/alerts/rules/'
    | '/$orgSlug/c/$connectionId/queues/$queueName/jobs/$jobId'
    | '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/$schedulerId'
    | '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-error'
    | '/consent'
    | '/login'
    | '/settings'
    | '/setup-organization'
    | '/signup'
    | '/$orgSlug/alerts'
    | '/$orgSlug/analytics'
    | '/$orgSlug/connections'
    | '/$orgSlug/redis-keys'
    | '/$orgSlug/scheduled-jobs'
    | '/$orgSlug/team'
    | '/$orgSlug/workers'
    | '/invite/$invitationId'
    | '/$orgSlug'
    | '/$orgSlug/settings/about'
    | '/$orgSlug/settings/appearance'
    | '/$orgSlug/settings/authentication'
    | '/$orgSlug/settings/connections'
    | '/$orgSlug/settings/destinations'
    | '/$orgSlug/settings/integrations'
    | '/$orgSlug/settings/team'
    | '/$orgSlug/settings'
    | '/$orgSlug/c/$connectionId/analytics'
    | '/$orgSlug/c/$connectionId/redis-keys'
    | '/$orgSlug/c/$connectionId/scheduled-jobs'
    | '/$orgSlug/c/$connectionId/workers'
    | '/$orgSlug/c/$connectionId'
    | '/$orgSlug/c/$connectionId/alerts/$ruleId'
    | '/$orgSlug/c/$connectionId/alerts/new'
    | '/$orgSlug/c/$connectionId/queues/$queueName'
    | '/$orgSlug/c/$connectionId/alerts'
    | '/$orgSlug/c/$connectionId/alerts/rules/$ruleId'
    | '/$orgSlug/c/$connectionId/alerts/rules'
    | '/$orgSlug/c/$connectionId/queues/$queueName/jobs/$jobId'
    | '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/$schedulerId'
    | '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/new'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/auth-error'
    | '/consent'
    | '/login'
    | '/settings'
    | '/setup-organization'
    | '/signup'
    | '/$orgSlug/alerts'
    | '/$orgSlug/analytics'
    | '/$orgSlug/connections'
    | '/$orgSlug/redis-keys'
    | '/$orgSlug/scheduled-jobs'
    | '/$orgSlug/settings'
    | '/$orgSlug/team'
    | '/$orgSlug/workers'
    | '/invite/$invitationId'
    | '/$orgSlug/'
    | '/$orgSlug/c/$connectionId'
    | '/$orgSlug/settings/about'
    | '/$orgSlug/settings/appearance'
    | '/$orgSlug/settings/authentication'
    | '/$orgSlug/settings/connections'
    | '/$orgSlug/settings/destinations'
    | '/$orgSlug/settings/integrations'
    | '/$orgSlug/settings/team'
    | '/$orgSlug/settings/'
    | '/$orgSlug/c/$connectionId/alerts'
    | '/$orgSlug/c/$connectionId/analytics'
    | '/$orgSlug/c/$connectionId/redis-keys'
    | '/$orgSlug/c/$connectionId/scheduled-jobs'
    | '/$orgSlug/c/$connectionId/workers'
    | '/$orgSlug/c/$connectionId/'
    | '/$orgSlug/c/$connectionId/alerts/$ruleId'
    | '/$orgSlug/c/$connectionId/alerts/new'
    | '/$orgSlug/c/$connectionId/queues/$queueName'
    | '/$orgSlug/c/$connectionId/alerts/'
    | '/$orgSlug/c/$connectionId/alerts/rules/$ruleId'
    | '/$orgSlug/c/$connectionId/alerts/rules/'
    | '/$orgSlug/c/$connectionId/queues/$queueName_/jobs/$jobId'
    | '/$orgSlug/c/$connectionId/queues/$queueName_/scheduled-jobs/$schedulerId'
    | '/$orgSlug/c/$connectionId/queues/$queueName_/scheduled-jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  AuthErrorRoute: typeof AuthErrorRoute
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SetupOrganizationRoute: typeof SetupOrganizationRoute
  SignupRoute: typeof SignupRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-organization': {
      id: '/setup-organization'
      path: '/setup-organization'
      fullPath: '/setup-organization'
      preLoaderRoute: typeof SetupOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/workers': {
      id: '/$orgSlug/workers'
      path: '/workers'
      fullPath: '/$orgSlug/workers'
      preLoaderRoute: typeof OrgSlugWorkersRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/team': {
      id: '/$orgSlug/team'
      path: '/team'
      fullPath: '/$orgSlug/team'
      preLoaderRoute: typeof OrgSlugTeamRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings': {
      id: '/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof OrgSlugSettingsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/scheduled-jobs': {
      id: '/$orgSlug/scheduled-jobs'
      path: '/scheduled-jobs'
      fullPath: '/$orgSlug/scheduled-jobs'
      preLoaderRoute: typeof OrgSlugScheduledJobsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/redis-keys': {
      id: '/$orgSlug/redis-keys'
      path: '/redis-keys'
      fullPath: '/$orgSlug/redis-keys'
      preLoaderRoute: typeof OrgSlugRedisKeysRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/connections': {
      id: '/$orgSlug/connections'
      path: '/connections'
      fullPath: '/$orgSlug/connections'
      preLoaderRoute: typeof OrgSlugConnectionsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/analytics': {
      id: '/$orgSlug/analytics'
      path: '/analytics'
      fullPath: '/$orgSlug/analytics'
      preLoaderRoute: typeof OrgSlugAnalyticsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/alerts': {
      id: '/$orgSlug/alerts'
      path: '/alerts'
      fullPath: '/$orgSlug/alerts'
      preLoaderRoute: typeof OrgSlugAlertsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/settings/': {
      id: '/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/team': {
      id: '/$orgSlug/settings/team'
      path: '/team'
      fullPath: '/$orgSlug/settings/team'
      preLoaderRoute: typeof OrgSlugSettingsTeamRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/integrations': {
      id: '/$orgSlug/settings/integrations'
      path: '/integrations'
      fullPath: '/$orgSlug/settings/integrations'
      preLoaderRoute: typeof OrgSlugSettingsIntegrationsRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/destinations': {
      id: '/$orgSlug/settings/destinations'
      path: '/destinations'
      fullPath: '/$orgSlug/settings/destinations'
      preLoaderRoute: typeof OrgSlugSettingsDestinationsRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/connections': {
      id: '/$orgSlug/settings/connections'
      path: '/connections'
      fullPath: '/$orgSlug/settings/connections'
      preLoaderRoute: typeof OrgSlugSettingsConnectionsRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/authentication': {
      id: '/$orgSlug/settings/authentication'
      path: '/authentication'
      fullPath: '/$orgSlug/settings/authentication'
      preLoaderRoute: typeof OrgSlugSettingsAuthenticationRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/appearance': {
      id: '/$orgSlug/settings/appearance'
      path: '/appearance'
      fullPath: '/$orgSlug/settings/appearance'
      preLoaderRoute: typeof OrgSlugSettingsAppearanceRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/settings/about': {
      id: '/$orgSlug/settings/about'
      path: '/about'
      fullPath: '/$orgSlug/settings/about'
      preLoaderRoute: typeof OrgSlugSettingsAboutRouteImport
      parentRoute: typeof OrgSlugSettingsRoute
    }
    '/$orgSlug/c/$connectionId': {
      id: '/$orgSlug/c/$connectionId'
      path: '/c/$connectionId'
      fullPath: '/$orgSlug/c/$connectionId'
      preLoaderRoute: typeof OrgSlugCConnectionIdRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/c/$connectionId/': {
      id: '/$orgSlug/c/$connectionId/'
      path: '/'
      fullPath: '/$orgSlug/c/$connectionId/'
      preLoaderRoute: typeof OrgSlugCConnectionIdIndexRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/workers': {
      id: '/$orgSlug/c/$connectionId/workers'
      path: '/workers'
      fullPath: '/$orgSlug/c/$connectionId/workers'
      preLoaderRoute: typeof OrgSlugCConnectionIdWorkersRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/scheduled-jobs': {
      id: '/$orgSlug/c/$connectionId/scheduled-jobs'
      path: '/scheduled-jobs'
      fullPath: '/$orgSlug/c/$connectionId/scheduled-jobs'
      preLoaderRoute: typeof OrgSlugCConnectionIdScheduledJobsRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/redis-keys': {
      id: '/$orgSlug/c/$connectionId/redis-keys'
      path: '/redis-keys'
      fullPath: '/$orgSlug/c/$connectionId/redis-keys'
      preLoaderRoute: typeof OrgSlugCConnectionIdRedisKeysRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/analytics': {
      id: '/$orgSlug/c/$connectionId/analytics'
      path: '/analytics'
      fullPath: '/$orgSlug/c/$connectionId/analytics'
      preLoaderRoute: typeof OrgSlugCConnectionIdAnalyticsRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/alerts': {
      id: '/$orgSlug/c/$connectionId/alerts'
      path: '/alerts'
      fullPath: '/$orgSlug/c/$connectionId/alerts'
      preLoaderRoute: typeof OrgSlugCConnectionIdAlertsRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/alerts/': {
      id: '/$orgSlug/c/$connectionId/alerts/'
      path: '/'
      fullPath: '/$orgSlug/c/$connectionId/alerts/'
      preLoaderRoute: typeof OrgSlugCConnectionIdAlertsIndexRouteImport
      parentRoute: typeof OrgSlugCConnectionIdAlertsRoute
    }
    '/$orgSlug/c/$connectionId/queues/$queueName': {
      id: '/$orgSlug/c/$connectionId/queues/$queueName'
      path: '/queues/$queueName'
      fullPath: '/$orgSlug/c/$connectionId/queues/$queueName'
      preLoaderRoute: typeof OrgSlugCConnectionIdQueuesQueueNameRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/alerts/new': {
      id: '/$orgSlug/c/$connectionId/alerts/new'
      path: '/new'
      fullPath: '/$orgSlug/c/$connectionId/alerts/new'
      preLoaderRoute: typeof OrgSlugCConnectionIdAlertsNewRouteImport
      parentRoute: typeof OrgSlugCConnectionIdAlertsRoute
    }
    '/$orgSlug/c/$connectionId/alerts/$ruleId': {
      id: '/$orgSlug/c/$connectionId/alerts/$ruleId'
      path: '/$ruleId'
      fullPath: '/$orgSlug/c/$connectionId/alerts/$ruleId'
      preLoaderRoute: typeof OrgSlugCConnectionIdAlertsRuleIdRouteImport
      parentRoute: typeof OrgSlugCConnectionIdAlertsRoute
    }
    '/$orgSlug/c/$connectionId/alerts/rules/': {
      id: '/$orgSlug/c/$connectionId/alerts/rules/'
      path: '/rules'
      fullPath: '/$orgSlug/c/$connectionId/alerts/rules/'
      preLoaderRoute: typeof OrgSlugCConnectionIdAlertsRulesIndexRouteImport
      parentRoute: typeof OrgSlugCConnectionIdAlertsRoute
    }
    '/$orgSlug/c/$connectionId/alerts/rules/$ruleId': {
      id: '/$orgSlug/c/$connectionId/alerts/rules/$ruleId'
      path: '/rules/$ruleId'
      fullPath: '/$orgSlug/c/$connectionId/alerts/rules/$ruleId'
      preLoaderRoute: typeof OrgSlugCConnectionIdAlertsRulesRuleIdRouteImport
      parentRoute: typeof OrgSlugCConnectionIdAlertsRoute
    }
    '/$orgSlug/c/$connectionId/queues/$queueName_/scheduled-jobs/new': {
      id: '/$orgSlug/c/$connectionId/queues/$queueName_/scheduled-jobs/new'
      path: '/queues/$queueName/scheduled-jobs/new'
      fullPath: '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/new'
      preLoaderRoute: typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/queues/$queueName_/scheduled-jobs/$schedulerId': {
      id: '/$orgSlug/c/$connectionId/queues/$queueName_/scheduled-jobs/$schedulerId'
      path: '/queues/$queueName/scheduled-jobs/$schedulerId'
      fullPath: '/$orgSlug/c/$connectionId/queues/$queueName/scheduled-jobs/$schedulerId'
      preLoaderRoute: typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
    '/$orgSlug/c/$connectionId/queues/$queueName_/jobs/$jobId': {
      id: '/$orgSlug/c/$connectionId/queues/$queueName_/jobs/$jobId'
      path: '/queues/$queueName/jobs/$jobId'
      fullPath: '/$orgSlug/c/$connectionId/queues/$queueName/jobs/$jobId'
      preLoaderRoute: typeof OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRouteImport
      parentRoute: typeof OrgSlugCConnectionIdRoute
    }
  }
}

interface OrgSlugSettingsRouteChildren {
  OrgSlugSettingsAboutRoute: typeof OrgSlugSettingsAboutRoute
  OrgSlugSettingsAppearanceRoute: typeof OrgSlugSettingsAppearanceRoute
  OrgSlugSettingsAuthenticationRoute: typeof OrgSlugSettingsAuthenticationRoute
  OrgSlugSettingsConnectionsRoute: typeof OrgSlugSettingsConnectionsRoute
  OrgSlugSettingsDestinationsRoute: typeof OrgSlugSettingsDestinationsRoute
  OrgSlugSettingsIntegrationsRoute: typeof OrgSlugSettingsIntegrationsRoute
  OrgSlugSettingsTeamRoute: typeof OrgSlugSettingsTeamRoute
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute
}

const OrgSlugSettingsRouteChildren: OrgSlugSettingsRouteChildren = {
  OrgSlugSettingsAboutRoute: OrgSlugSettingsAboutRoute,
  OrgSlugSettingsAppearanceRoute: OrgSlugSettingsAppearanceRoute,
  OrgSlugSettingsAuthenticationRoute: OrgSlugSettingsAuthenticationRoute,
  OrgSlugSettingsConnectionsRoute: OrgSlugSettingsConnectionsRoute,
  OrgSlugSettingsDestinationsRoute: OrgSlugSettingsDestinationsRoute,
  OrgSlugSettingsIntegrationsRoute: OrgSlugSettingsIntegrationsRoute,
  OrgSlugSettingsTeamRoute: OrgSlugSettingsTeamRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
}

const OrgSlugSettingsRouteWithChildren = OrgSlugSettingsRoute._addFileChildren(
  OrgSlugSettingsRouteChildren,
)

interface OrgSlugCConnectionIdAlertsRouteChildren {
  OrgSlugCConnectionIdAlertsRuleIdRoute: typeof OrgSlugCConnectionIdAlertsRuleIdRoute
  OrgSlugCConnectionIdAlertsNewRoute: typeof OrgSlugCConnectionIdAlertsNewRoute
  OrgSlugCConnectionIdAlertsIndexRoute: typeof OrgSlugCConnectionIdAlertsIndexRoute
  OrgSlugCConnectionIdAlertsRulesRuleIdRoute: typeof OrgSlugCConnectionIdAlertsRulesRuleIdRoute
  OrgSlugCConnectionIdAlertsRulesIndexRoute: typeof OrgSlugCConnectionIdAlertsRulesIndexRoute
}

const OrgSlugCConnectionIdAlertsRouteChildren: OrgSlugCConnectionIdAlertsRouteChildren =
  {
    OrgSlugCConnectionIdAlertsRuleIdRoute:
      OrgSlugCConnectionIdAlertsRuleIdRoute,
    OrgSlugCConnectionIdAlertsNewRoute: OrgSlugCConnectionIdAlertsNewRoute,
    OrgSlugCConnectionIdAlertsIndexRoute: OrgSlugCConnectionIdAlertsIndexRoute,
    OrgSlugCConnectionIdAlertsRulesRuleIdRoute:
      OrgSlugCConnectionIdAlertsRulesRuleIdRoute,
    OrgSlugCConnectionIdAlertsRulesIndexRoute:
      OrgSlugCConnectionIdAlertsRulesIndexRoute,
  }

const OrgSlugCConnectionIdAlertsRouteWithChildren =
  OrgSlugCConnectionIdAlertsRoute._addFileChildren(
    OrgSlugCConnectionIdAlertsRouteChildren,
  )

interface OrgSlugCConnectionIdRouteChildren {
  OrgSlugCConnectionIdAlertsRoute: typeof OrgSlugCConnectionIdAlertsRouteWithChildren
  OrgSlugCConnectionIdAnalyticsRoute: typeof OrgSlugCConnectionIdAnalyticsRoute
  OrgSlugCConnectionIdRedisKeysRoute: typeof OrgSlugCConnectionIdRedisKeysRoute
  OrgSlugCConnectionIdScheduledJobsRoute: typeof OrgSlugCConnectionIdScheduledJobsRoute
  OrgSlugCConnectionIdWorkersRoute: typeof OrgSlugCConnectionIdWorkersRoute
  OrgSlugCConnectionIdIndexRoute: typeof OrgSlugCConnectionIdIndexRoute
  OrgSlugCConnectionIdQueuesQueueNameRoute: typeof OrgSlugCConnectionIdQueuesQueueNameRoute
  OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRoute: typeof OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRoute
  OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRoute: typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRoute
  OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRoute: typeof OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRoute
}

const OrgSlugCConnectionIdRouteChildren: OrgSlugCConnectionIdRouteChildren = {
  OrgSlugCConnectionIdAlertsRoute: OrgSlugCConnectionIdAlertsRouteWithChildren,
  OrgSlugCConnectionIdAnalyticsRoute: OrgSlugCConnectionIdAnalyticsRoute,
  OrgSlugCConnectionIdRedisKeysRoute: OrgSlugCConnectionIdRedisKeysRoute,
  OrgSlugCConnectionIdScheduledJobsRoute:
    OrgSlugCConnectionIdScheduledJobsRoute,
  OrgSlugCConnectionIdWorkersRoute: OrgSlugCConnectionIdWorkersRoute,
  OrgSlugCConnectionIdIndexRoute: OrgSlugCConnectionIdIndexRoute,
  OrgSlugCConnectionIdQueuesQueueNameRoute:
    OrgSlugCConnectionIdQueuesQueueNameRoute,
  OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRoute:
    OrgSlugCConnectionIdQueuesQueueNameJobsJobIdRoute,
  OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRoute:
    OrgSlugCConnectionIdQueuesQueueNameScheduledJobsSchedulerIdRoute,
  OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRoute:
    OrgSlugCConnectionIdQueuesQueueNameScheduledJobsNewRoute,
}

const OrgSlugCConnectionIdRouteWithChildren =
  OrgSlugCConnectionIdRoute._addFileChildren(OrgSlugCConnectionIdRouteChildren)

interface OrgSlugRouteChildren {
  OrgSlugAlertsRoute: typeof OrgSlugAlertsRoute
  OrgSlugAnalyticsRoute: typeof OrgSlugAnalyticsRoute
  OrgSlugConnectionsRoute: typeof OrgSlugConnectionsRoute
  OrgSlugRedisKeysRoute: typeof OrgSlugRedisKeysRoute
  OrgSlugScheduledJobsRoute: typeof OrgSlugScheduledJobsRoute
  OrgSlugSettingsRoute: typeof OrgSlugSettingsRouteWithChildren
  OrgSlugTeamRoute: typeof OrgSlugTeamRoute
  OrgSlugWorkersRoute: typeof OrgSlugWorkersRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugCConnectionIdRoute: typeof OrgSlugCConnectionIdRouteWithChildren
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugAlertsRoute: OrgSlugAlertsRoute,
  OrgSlugAnalyticsRoute: OrgSlugAnalyticsRoute,
  OrgSlugConnectionsRoute: OrgSlugConnectionsRoute,
  OrgSlugRedisKeysRoute: OrgSlugRedisKeysRoute,
  OrgSlugScheduledJobsRoute: OrgSlugScheduledJobsRoute,
  OrgSlugSettingsRoute: OrgSlugSettingsRouteWithChildren,
  OrgSlugTeamRoute: OrgSlugTeamRoute,
  OrgSlugWorkersRoute: OrgSlugWorkersRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugCConnectionIdRoute: OrgSlugCConnectionIdRouteWithChildren,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  AuthErrorRoute: AuthErrorRoute,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SetupOrganizationRoute: SetupOrganizationRoute,
  SignupRoute: SignupRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
